config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  path: '',
                      path_names: {
                        sign_in: 'sign-in',
                      },
                      controllers: {
                        registrations: 'users/registrations',
                        confirmations: 'users/confirmations',
                      },
                      skip: [
                        :registrations,
                      ],
                      skip_helpers: true

  devise_scope :user do
    get '/register', to: redirect('/sign-in'), as: :register_without_type
    get '/register/:type', to: 'users/registrations#new', as: :registration
    post '/register/:type', to: 'users/registrations#create'
    get '/register/:type/confirm', to: 'users/registrations#confirm', as: :registration_confirm

    get '/account', to: 'users/registrations#edit', as: :edit_account
    put '/account', to: 'users/registrations#update', as: :account
  end

  namespace :sellers do
    resources :applications, only: [:new, :create, :show, :update], controller: 'applications/root' do
      member do
        get :submit
        post :submit, to: 'applications/root#do_submit'
      end

      resources :products, controller: 'applications/products' do
        member do
          post :clone
        end
      end
      get '/products/:id/:step', to: 'applications/products#edit', as: :product_step
      patch '/products/:id/:step', to: 'applications/products#update'

      resources :invitations, controller: 'applications/invitations', only: [:index, :new, :create] do
        collection do
          get :accept
          patch '/accept', to: 'applications/invitations#update_accept', as: :update_accept
        end
      end
    end
    get '/applications/:id/:step', to: 'applications/steps#show', as: :application_step
    patch '/applications/:id/:step', to: 'applications/steps#update'

    resources :profiles, only: :show
    resources :waitlist_invitations, path: 'waitlist', only: :show do
      patch :accept, on: :member
    end

    get '/search', to: 'search#search', as: :search
    get '/dashboard', to: 'dashboard#show', as: :dashboard
  end

  namespace :buyers do
    resources :applications
    get '/applications/:id/manager-approve', to: 'applications#manager_approve', as: :manager_approve_application
    get '/applications/:id/:step', to: 'applications#show', as: :application_step

    get '/dashboard', to: 'dashboard#show', as: :dashboard
    scope 'products/:id' do
      resources :product_orders, only: [:new, :create], path: 'orders'
    end
  end

  get '/cloud', to: 'static#cloud', as: :cloud
  get '/cloud/:section', to: 'pathways/search#search', as: :pathway_search
  get '/cloud/:section/products/:id', to: 'pathways/products#show', as: :pathway_product

  namespace :ops do
    resources :buyers do
      member do
        get :details
        post :deactivate
      end
    end

    resources :buyer_applications, path: 'buyer-applications' do
      member do
        get :buyer_details

        patch :assign
        patch :decide
        post :notes
      end
    end

    resources :sellers, only: [:index]

    resources :seller_applications, path: 'seller-applications', controller: 'seller_versions' do
      member do
        get :seller_details
        get :documents

        patch :assign
        patch :decide
        post :notes
      end

      resources :products, only: :show, controller: 'seller_versions/products'
    end

    resources :waiting_sellers, path: 'waiting-sellers' do
      collection do
        post :upload, to: 'waiting_sellers#upload'
        get :invite, to: 'waiting_sellers#invite'
        post :invite, to: 'waiting_sellers#do_invite'
      end
    end

    resources :problem_reports, path: 'problem-reports', only: [:index, :show] do
      member do
        post :resolve
        put :tag
      end
    end

    resources :product_orders, only: :index, path: 'product-orders'

    root to: 'root#index'
  end

  namespace :feedback do
    resources :problem_reports, path: 'problem-reports', only: [:new, :create]
  end

  get '/performance', to: 'performance#index'

  get '/contact', to: 'static#contact'
  get '/join-mailing-list', to: 'static#join_mailing_list'
  get '/privacy', to: 'static#privacy'
  get '/terms-of-use', to: 'static#terms_of_use'
  get '/accessibility', to: 'static#accessibility'
  get '/core-terms', to: 'static#core_terms'
  get '/guides/seller', to: 'static#seller_guide'
  get '/guides/buyer', to: 'static#buyer_guide'
  get '/license', to: 'static#license'
  # Health check page for load balancer - never use basic auth
  get '/health', to: 'static#health'
  get '/govdc', to: 'static#govdc'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root to: redirect('/cloud')
end

app/controllers/ops/base_controller.rb
class Ops::BaseController < ApplicationController
  before_action :authenticate_admin!

  layout 'ops'

private
  def authenticate_admin!
    unless current_user && current_user.is_admin?
      raise NotAuthorized
    end
  end

  def set_content_disposition
    response.headers['Content-Disposition'] = "attachment; filename=#{csv_filename}"
  end

end

app/controllers/ops/buyer_applications_controller.rb
class Ops::BuyerApplicationsController < Ops::BaseController

  after_action :set_content_disposition, if: :csv_request?, only: :index

  layout ->{
    action_name == 'index' ? 'ops' : '../ops/buyer_applications/_layout'
  }

  def index
    respond_to do |format|
      format.html
      format.csv
    end
  end

  def assign
    operation = Ops::AssignBuyerApplication.call(
      buyer_application_id: params[:id],
      current_user: current_user,
      attributes: params[:buyer_application],
    )

    if operation.success?
      flash.notice = I18n.t('ops.buyer_applications.messages.update_assign_success')
      return redirect_to ops_buyer_application_path(application)
    else
      render :show
    end
  end

  def decide
    operation = Ops::DecideBuyerApplication.call(
      buyer_application_id: params[:id],
      current_user: current_user,
      attributes: params[:buyer_application],
    )

    if operation.success?
      decision = operation.form.decision
      flash.notice = I18n.t("ops.buyer_applications.messages.decision_success.#{decision}")
      return redirect_to ops_buyer_application_path(application)
    else
      render :show
    end
  end

  def notes
    application = BuyerApplication.find(params[:id])
    event = Event::Note.create(
      user: current_user,
      eventable: application,
      note: params[:event_note]['note']
    )
    redirect_to ops_buyer_application_path(application)
  end

private
  def search
    @search ||= Search::BuyerApplication.new(
      selected_filters: params,
      default_values: {
        state: 'ready_for_review',
        assigned_to: current_user.id,
      },
      page: params.fetch(:page, 1),
      per_page: 25,
    )
  end
  helper_method :search

  def application
    @application ||= BuyerApplication.find(params[:id])
  end
  helper_method :application

  def assign_form
    @assign_form ||= Ops::BuildAssignBuyerApplication.call(buyer_application_id: params[:id]).form
  end
  helper_method :assign_form

  def decide_form
    @decide_form ||= Ops::BuildDecideBuyerApplication.call(buyer_application_id: params[:id]).form
  end
  helper_method :decide_form

  def csv_filename
    "buyer-applications-#{search.selected_filters_string}-#{Time.now.to_i}.csv"
  end
end

app/controllers/ops/buyers_controller.rb
class Ops::BuyersController < Ops::BaseController

  after_action :set_content_disposition, if: :csv_request?, only: :index

  layout ->{
    action_name == 'index' ? 'ops' : '../ops/buyers/_layout'
  }

  def index
    respond_to do |format|
      format.html
      format.csv
    end
  end

  def deactivate
    operation = Ops::DeactivateBuyer.call(buyer_id: params[:id])

    if operation.success?
      flash.notice = I18n.t('ops.buyers.messages.deactivate_success')
      return redirect_to ops_buyer_path(buyer)
    else
      render :show
    end
  end

private
  def search
    @search ||= Search::Buyer.new(
      selected_filters: params,
      default_values: {
        state: 'active',
      },
      page: params.fetch(:page, 1),
      per_page: 25,
    )
  end
  helper_method :search

  def buyer
    @buyer ||= Buyer.find(params[:id])
  end
  helper_method :buyer

  def csv_filename
    "buyers-#{search.selected_filters_string}-#{Time.now.to_i}.csv"
  end
end

app/controllers/ops/problem_reports_controller.rb
class Ops::ProblemReportsController < Ops::BaseController

  def index; end
  def show; end

  def resolve
    operation = run Ops::ProblemReport::Resolve

    if operation.success?
      flash.notice = I18n.t('ops.problem_reports.messages.resolved')
    else
      flash.alert = I18n.t('ops.problem_reports.messages.resolve_failed')
    end

    redirect_to ops_problem_report_path(operation['model'])
  end

  def tag
    operation = run Ops::ProblemReport::Tag

    if operation.success?
      flash.notice = I18n.t('ops.problem_reports.messages.updated')
    else
      flash.alert = I18n.t('ops.problem_reports.messages.update_failed')
    end

    redirect_to ops_problem_report_path(operation['model'])
  end

private
  def search
    @search ||= Search::ProblemReport.new(
      selected_filters: params,
      default_values: {
        state: 'open',
      },
      page: params.fetch(:page, 1),
      per_page: 25,
    )
  end

  def problem_report
    @problem_report ||= ProblemReport.find(params[:id])
  end

  def operations
    {
      tag: run(Ops::ProblemReport::Tag::Present),
    }
  end

  helper_method :search, :problem_report, :operations

  def _run_options(options)
    options.merge('config.current_user' => current_user)
  end

end

app/controllers/ops/product_orders_controller.rb
class Ops::ProductOrdersController < Ops::BaseController
  def index
  end

private
  def search
    @search ||= Search::ProductOrders.new(
      selected_filters: params,
      default_values: {},
      page: params.fetch(:page, 1),
      per_page: 25,
    )
  end
  helper_method :search

end

app/controllers/ops/root_controller.rb
class Ops::RootController < Ops::BaseController

  def index
  end

end

app/controllers/ops/seller_applications/products_controller.rb
class Ops::SellerApplications::ProductsController < Ops::BaseController
  layout '../ops/seller_applications/_layout'

  def show
  end

private
  def application
    @application ||= SellerVersion.find(params[:seller_application_id])
  end
  helper_method :application

  def product
    @product ||= ProductDecorator.new(
      application.seller.products.find(params[:id]),
      view_context,
    )
  end
  helper_method :product
end

app/controllers/ops/seller_applications_controller.rb
class Ops::SellerApplicationsController < Ops::BaseController

  after_action :set_content_disposition, if: :csv_request?, only: :index

  layout ->{
    action_name == 'index' ? 'ops' : '../ops/seller_applications/_layout'
  }

  def index
    respond_to do |format|
      format.html
      format.csv
    end
  end

  def show
  end

  def assign
    run Ops::SellerApplication::Assign do |result|
      flash.notice = I18n.t('ops.seller_applications.messages.update_assign_success')
      return redirect_to ops_seller_application_path(application)
    end

    render :show
  end

  def decide
    run Ops::SellerApplication::Decide do |result|
      decision = result['contract.default'].decision
      flash.notice = I18n.t("ops.seller_applications.messages.decision_success.#{decision}")
      return redirect_to ops_seller_application_path(application)
    end

    render :show
  end

  def notes
    application = SellerVersion.find(params[:id])
    event = Event::Note.create(
      user: current_user,
      eventable: application,
      note: params[:event_note]['note']
    )
    redirect_to ops_seller_application_path(application)
  end

private
  def applications
    @applications ||= SellerVersion.includes(:seller)
  end
  helper_method :applications

  def search
    @search ||= Search::SellerVersion.new(
      selected_filters: params,
      default_values: {
        state: 'ready_for_review',
        assigned_to: current_user.id,
      },
      page: params.fetch(:page, 1),
      per_page: 25,
    )
  end
  helper_method :search

  def application
    @application ||= SellerVersion.find(params[:id])
  end
  helper_method :application

  def decorated_seller
    SellerDecorator.new(application.seller, view_context)
  end
  helper_method :decorated_seller

  def forms
    @forms ||= {
      assign: ops[:assign]['contract.default'],
      decide: ops[:decide]['contract.default'],
    }
  end
  helper_method :forms

  def ops
    @ops ||= {
      assign: (run Ops::SellerApplication::Assign::Present),
      decide: (run Ops::SellerApplication::Decide::Present),
    }
  end

  def _run_options(options)
    options.merge( "current_user" => current_user )
  end

  def csv_filename
    "seller-applications-#{search.selected_filters_string}-#{Time.now.to_i}.csv"
  end
end

app/controllers/ops/seller_versions/products_controller.rb
class Ops::SellerVersions::ProductsController < Ops::BaseController
  layout '../ops/seller_versions/_layout'

  def show
  end

private
  def application
    @application ||= SellerVersion.find(params[:seller_application_id])
  end
  helper_method :application

  def product
    @product ||= ProductDecorator.new(
      application.seller.products.find(params[:id]),
      view_context,
    )
  end
  helper_method :product
end

app/controllers/ops/seller_versions_controller.rb
class Ops::SellerVersionsController < Ops::BaseController

  after_action :set_content_disposition, if: :csv_request?, only: :index

  layout ->{
    action_name == 'index' ? 'ops' : '../ops/seller_versions/_layout'
  }

  def index
    respond_to do |format|
      format.html
      format.csv
    end
  end

  def show
  end

  def assign
    run Ops::SellerVersion::Assign do |result|
      flash.notice = I18n.t('ops.seller_versions.messages.update_assign_success')
      return redirect_to ops_seller_application_path(application)
    end

    render :show
  end

  def decide
    run Ops::SellerVersion::Decide do |result|
      decision = result['contract.default'].decision
      flash.notice = I18n.t("ops.seller_versions.messages.decision_success.#{decision}")
      return redirect_to ops_seller_application_path(application)
    end

    render :show
  end

  def notes
    application = SellerVersion.find(params[:id])
    event = Event::Note.create(
      user: current_user,
      eventable: application,
      note: params[:event_note]['note']
    )
    redirect_to ops_seller_application_path(application)
  end

private
  def applications
    @applications ||= SellerVersion.includes(:seller)
  end
  helper_method :applications

  def search
    @search ||= Search::Ops::SellerVersion.new(
      selected_filters: params,
      default_values: {
        state: 'ready_for_review',
        assigned_to: current_user.id,
      },
      page: params.fetch(:page, 1),
      per_page: 25,
    )
  end
  helper_method :search

  def application
    @application ||= SellerVersion.find(params[:id])
  end
  helper_method :application

  def decorated_seller
    SellerDecorator.new(application.seller, view_context)
  end
  helper_method :decorated_seller

  def forms
    @forms ||= {
      assign: ops[:assign]['contract.default'],
      decide: ops[:decide]['contract.default'],
    }
  end
  helper_method :forms

  def ops
    @ops ||= {
      assign: (run Ops::SellerVersion::Assign::Present),
      decide: (run Ops::SellerVersion::Decide::Present),
    }
  end

  def _run_options(options)
    options.merge( "current_user" => current_user )
  end

  def csv_filename
    "seller-applications-#{search.selected_filters_string}-#{Time.now.to_i}.csv"
  end
end

app/controllers/ops/sellers_controller.rb
class Ops::SellersController < Ops::BaseController

  after_action :set_content_disposition, if: :csv_request?, only: :index

  def index
    respond_to do |format|
      format.html
      format.csv
    end
  end

private
  def search
    @search ||= Search::Ops::Seller.new(
      selected_filters: params,
      default_values: {
        state: 'active',
      },
      page: params.fetch(:page, 1),
      per_page: 25,
    )
  end
  helper_method :search

  def csv_filename
    "sellers-#{search.selected_filters_string}-#{Time.now.to_i}.csv"
  end
end

app/helpers/ops/assignees_helper.rb
module Ops::AssigneesHelper
  def available_assignees
    User.admin
  end
end

app/helpers/ops/base_helper.rb
module Ops::BaseHelper
  include NavigationHelper
  include FiltersHelper
end

app/helpers/ops/buyer_applications/detail_helper.rb
module Ops::BuyerApplications::DetailHelper
  def display_buyer_list(type:, resource:)
    display_list(
      fields: buyer_fields,
      resource_name: :buyer_applications,
      type: type,
      resource: resource,
    )
  end

  def buyer_fields
    {
      basic: [
        :name,
        :organisation,
        :employment_status,
      ],
      application: [
        :application_body,
      ],
      manager: [
        :manager_name,
        :manager_email,
      ]
    }
  end

end

app/helpers/ops/buyer_applications_helper.rb
module Ops::BuyerApplicationsHelper
  include Ops::AssigneesHelper
  include Ops::DetailHelper

  include Ops::BuyerApplications::DetailHelper
end

app/views/ops/seller_versions/_address_details.html.erb
<dl>
  <dt><%= t('ops.seller_applications.fields.addresses.name') %></dt>
  <dd>
    <ul>
      <% seller.addresses.each do |address| %>
        <li>
          <%= address.address %><br>
          <%= address.suburb %><br>
          <%= address.state_text %><br>
          <%= address.postcode %><br>
          <%= address.country %>
        </li>
      <% end %>
    </ul>
  </dd>
</dl>

app/views/ops/seller_versions/_assign_form.html.erb
<%= buy_nsw_form_for form, url: assign_ops_seller_application_path(form.model), i18n_scope: 'ops.seller_versions.forms.assign' do |f| %>
  <%= f.input :assigned_to_id, as: :select, collection: available_assignees, label_method: :email, value_method: :id, include_blank: false %>
  <%= f.submit 'Assign' %>
<% end %>

app/views/ops/seller_versions/_business_info_details.html.erb
<dl>
  <dt><%= t('ops.seller_versions.fields.government_experience.name') %></dt>
  <dd>
    <%= government_experience_values(seller) %>
  </dd>
</dl>

app/views/ops/seller_versions/_decision_form.html.erb
<%= buy_nsw_form_for form, url: decide_ops_seller_application_path(form.model), i18n_scope: 'ops.seller_versions.forms.decision' do |f| %>
  <%= f.input :decision, as: :radio_buttons, collection: form_options_with_labels(f.i18n_scope, :decision, [:approve, :return_to_applicant, :reject]) %>
  <%= f.input :response, as: :text, input_html: { rows: 5 } %>

  <%= f.submit 'Make decision' %>
<% end %>

app/views/ops/seller_versions/_document.html.erb
<li class="document">
  <header>
    <h3><%= t("ops.seller_versions.fields.#{key}.name", default: key) %></h3>
  </header>

  <div class="document-details">
    <% if key == :workers_compensation_certificate && application.seller.workers_compensation_exempt %>
      <p>Not required to have workers compensation insurance.</p>
    <% else %>
      <% if (expiry = application.seller.send("#{key}_expiry")) && expiry.present? %>
        <p>
          <% if local_assigns[:no_expiry] %>
            Document date:
          <% else %>
            Expiry date:
          <% end %>

          <%= expiry.strftime('%d %b %Y') %>
          (<%= time_ago_in_words(expiry) %> <%= expiry > Time.now ? 'from now' : 'ago' %>)
        </p>
      <% end %>

      <% if (upload = application.seller.send(key)) && upload.document.present? %>
        <p class="file-name"><%= upload.original_filename %></p>

        <% if file_clean?(upload) %>
          <p>
            <%= link_to upload.url, class: 'btn btn-primary', target: '_blank' do %>
              View document (<%= upload.extension %>, <%= number_to_human_size(upload.size) %>)
            <% end %>
          </p>
        <% else %>
          <p class="scan-status">
            <%= upload.scan_status_text %>
          </p>
        <% end %>
      <% else %>
        <p>Document not provided.</p>
      <% end %>
    <% end %>
  </div>
</li>

app/views/ops/seller_versions/_layout.html.erb
<% content_for(:ops_content) do %>
  <section class="view-ops-seller-applications-show">
    <div class="column-set">
      <aside>
        <h1>
          <span class="type">Seller application</span>
          <%= application.seller.name %>
        </h1>
        <nav class="vertical">
          <ul>
            <%= nav_link_to 'Application', ops_seller_application_path(application), icon: 'ellipses' %>
            <%= nav_link_to 'Seller details', seller_details_ops_seller_application_path(application), icon: 'spreadsheet' %>
            <%= nav_link_to 'Documents', documents_ops_seller_application_path(application), icon: 'file' %>
          </ul>

          <h3>
            Cloud products and support:
            <%= pluralize application.seller.products.count, 'product' %>
          </h3>
          <ul>
            <% application.seller.products.each do |product| %>
              <%= nav_link_to formatted_product_name(product), ops_seller_application_product_path(application, product), icon: 'cart' %>
            <% end %>
          </ul>
        </nav>
      </aside>

      <div class="current-view">
        <%= content_for?(:seller_application_content) ? yield(:seller_application_content) : yield %>
      </div>
    </div>
  </section>
<% end %>

<%= render template: 'layouts/ops' %>

app/views/ops/seller_versions/_list.html.erb
<% if applications.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Seller name</th>
        <th scope="col">Status</th>
        <th scope="col">Submitted</th>
        <th scope="col">Assigned to</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% applications.each do |application| %>
      <tr>
        <td><%= application.id %></td>
        <td>
          <% if application.seller.name.present? %>
            <%= application.seller.name %>
          <% else %>
            <em>Unnamed seller (<%= application.seller.owners.first.email %>)</em>
          <% end %>
        </td>
        <td><%= application.state %></td>
        <td>
          <% if application.submitted_at.present? %>
            <abbr title="<%= application.submitted_at.to_s %>">
              <%= time_ago_in_words application.submitted_at %> ago
            </abbr>
          <% end %>
        </td>
        <td>
          <% if application.assigned_to.present? %>
            <%= application.assigned_to.email %>
          <% end %>
        </td>
        <td class="actions">
          <%= link_to 'View', ops_seller_application_path(application) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <%= render partial: 'ops/shared/no_records_message', locals: local_assigns.slice(:search) %>
<% end %>

app/views/ops/seller_versions/_note_form.html.erb
<%= buy_nsw_form_for event, url: notes_ops_seller_application_path(application), i18n_scope: 'ops.seller_versions.forms.note' do |f| %>
  <%= f.input :note, as: :text, input_html: { rows: 5 } %>
  <p>This <strong>will be visible</strong> to other ops user and <strong>not visible</strong> to the applicant.</p>

  <%= f.submit 'Add Note' %>
<% end %>

app/views/ops/seller_versions/_recognition_details.html.erb
<dl>
  <% [:accreditations, :engagements, :awards].each do |kind| %>
    <dt><%= t(:name, scope: [:ops, :seller_versions, :fields, kind]) %></dt>
    <dd>
      <% if seller.public_send(kind).any? %>
        <ul>
          <% seller.public_send(kind).each do |item| %>
            <li><%= item.send(kind.to_s.singularize) %></li>
          <% end %>
        </ul>
      <% else %>
        <em>None</em>
      <% end %>
    </dd>
  <% end %>
</dl>

app/views/ops/seller_versions/assign.html.erb
<%= render partial: 'assign_form', locals: { application: application } %>

app/views/ops/seller_versions/documents.html.erb
<h2>Uploaded documents</h2>

<ul class="documents">
  <%= render partial: 'document', locals: { key: :financial_statement, no_expiry: true } %>
  <%= render partial: 'document', locals: { key: :professional_indemnity_certificate } %>
  <%= render partial: 'document', locals: { key: :product_liability_certificate } %>
  <%= render partial: 'document', locals: { key: :workers_compensation_certificate } %>
</ul>

app/views/ops/seller_versions/index.html.erb
<% content_for(:ops_content) do %>
<section class="view-ops-seller-applications-list">
  <div class="column-set">
    <aside>
      <h1>Seller applications</h1>

      <%= render partial: 'ops/shared/filters', locals: { search: search } %>
    </aside>

    <div class="current-view">
      <section class="record-list">
        <header>
          <h2><%= pluralize(search.result_count, 'application') %></h2>
          <% if search.results.any? %>
            <div class="list-actions">
              <%= link_to(
                    t(:export_csv, scope: [:ops, :seller_versions, :search, :labels]),
                    ops_seller_applications_path({ format: :csv }.merge(search.selected_filters)),
                  ) %>
            </div>
          <% end %>
        </header>

        <%= render partial: 'list', locals: {
              search: search,
              applications: search.paginated_results,
            } %>
        <%= paginate search.paginated_results %>
      </section>
    </div>
  </div>
</section>
<% end %>

app/views/ops/seller_versions/seller_details.html.erb
<h2>Seller details</h2>

<%= display_seller_list(type: :basic, resource: decorated_seller) %>
<%= display_seller_list(type: :industry, resource: decorated_seller) %>
<%= render partial: 'address_details', locals: { seller: decorated_seller } %>
<%= display_seller_list(type: :contacts, resource: decorated_seller) %>
<%= display_seller_list(type: :disclosures, resource: decorated_seller) %>
<%= display_seller_list(type: :details, resource: decorated_seller) %>
<%= render partial: 'business_info_details', locals: { seller: decorated_seller } %>
<%= render partial: 'recognition_details', locals: { seller: decorated_seller } %>
<%= display_seller_list(type: :terms, resource: decorated_seller) %>

app/views/ops/seller_versions/show.html.erb
<% content_for(:seller_application_content) do %>
  <section class="status-overview">
    <div class="status-indicator">
      <span>Status</span>
      <%= application.state %>
    </div>
    <div class="assigned-to">
      <span>Assigned to</span>
      <% if application.assigned_to.present? %>
        <%= application.assigned_to.email %>
      <% else %>
        nobody
      <% end %>
    </div>
  </section>

  <section class="application-details">
    <% if application.seller.waiting_seller.present? %>
      <p class="invited-message">This seller was invited to apply.</p>
    <% end %>
    <dl>
      <% if application.started_at.present? %>
        <dt>Started at</dt>
        <dd><%= application.started_at.localtime.to_formatted_s(:long) %></dd>
      <% end %>
      <% if application.submitted_at.present? %>
        <dt>Submitted by</dt>
        <dd><%= application.owners.map(&:email).join(', ') %></dd>
        <dt>Submitted at</dt>
        <dd><%= application.submitted_at.localtime.to_formatted_s(:long) %></dd>
      <% end %>
      <% if application.decided_at.present? %>
        <dt>Decided at</dt>
        <dd><%= application.decided_at.localtime.to_formatted_s(:long) %></dd>
      <% end %>
    </dl>
  </section>

  <section class="make-assignment" data-module="collapsible-section">
    <h2>Assign this application to a user</h2>

    <div class="inner">
      <%= render partial: 'assign_form', locals: { form: forms[:assign] } %>
    </div>
  </section>

  <% if application.may_approve? && application.assigned_to == current_user %>
    <section class="make-decision" data-module="collapsible-section">
      <h2>Make a decision on this application</h2>

      <div class="inner">
        <%= render partial: 'decision_form', locals: { form: forms[:decide] } %>
      </div>
    </section>
  <% end %>

  <section class="add-note" data-module="collapsible-section">
    <h2>Add a private note to this application</h2>

    <div class="inner">
      <%= render partial: 'note_form', locals: { event: Event::Note.new, application: application } %>
    </div>
  </section>

  <section class="events-list">
    <% if application.events.any? %>
      <h2>History</h2>
      <%= render partial: 'ops/shared/events', locals: { events: application.events } %>
    <% end %>
  </section>
<% end %>