config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  path: '',
                      path_names: {
                        sign_in: 'sign-in',
                      },
                      controllers: {
                        registrations: 'users/registrations',
                        confirmations: 'users/confirmations',
                      },
                      skip: [
                        :registrations,
                      ],
                      skip_helpers: true

  devise_scope :user do
    get '/register', to: redirect('/sign-in'), as: :register_without_type
    get '/register/:type', to: 'users/registrations#new', as: :registration
    post '/register/:type', to: 'users/registrations#create'
    get '/register/:type/confirm', to: 'users/registrations#confirm', as: :registration_confirm

    get '/account', to: 'users/registrations#edit', as: :edit_account
    put '/account', to: 'users/registrations#update', as: :account
  end

  namespace :sellers do
    resources :applications, only: [:new, :create, :show, :update], controller: 'applications/root' do
      member do
        get :submit
        post :submit, to: 'applications/root#do_submit'
      end

      resources :products, controller: 'applications/products' do
        member do
          post :clone
        end
      end
      get '/products/:id/:step', to: 'applications/products#edit', as: :product_step
      patch '/products/:id/:step', to: 'applications/products#update'

      resources :invitations, controller: 'applications/invitations', only: [:index, :new, :create] do
        collection do
          get :accept
          patch '/accept', to: 'applications/invitations#update_accept', as: :update_accept
        end
      end
    end
    get '/applications/:id/:step', to: 'applications/steps#show', as: :application_step
    patch '/applications/:id/:step', to: 'applications/steps#update'

    resources :profiles, only: :show
    resources :waitlist_invitations, path: 'waitlist', only: :show do
      patch :accept, on: :member
    end

    get '/search', to: 'search#search', as: :search
    get '/dashboard', to: 'dashboard#show', as: :dashboard
  end

  namespace :buyers do
    resources :applications
    get '/applications/:id/manager-approve', to: 'applications#manager_approve', as: :manager_approve_application
    get '/applications/:id/:step', to: 'applications#show', as: :application_step

    get '/dashboard', to: 'dashboard#show', as: :dashboard
    scope 'products/:id' do
      resources :product_orders, only: [:new, :create], path: 'orders'
    end
  end

  get '/cloud', to: 'static#cloud', as: :cloud
  get '/cloud/:section', to: 'pathways/search#search', as: :pathway_search
  get '/cloud/:section/products/:id', to: 'pathways/products#show', as: :pathway_product

  namespace :ops do
    resources :buyers do
      member do
        get :details
        post :deactivate
      end
    end

    resources :buyer_applications, path: 'buyer-applications' do
      member do
        get :buyer_details

        patch :assign
        patch :decide
        post :notes
      end
    end

    resources :sellers, only: [:index]

    resources :seller_applications, path: 'seller-applications', controller: 'seller_versions' do
      member do
        get :seller_details
        get :documents

        patch :assign
        patch :decide
        post :notes
      end

      resources :products, only: :show, controller: 'seller_versions/products'
    end

    resources :waiting_sellers, path: 'waiting-sellers' do
      collection do
        post :upload, to: 'waiting_sellers#upload'
        get :invite, to: 'waiting_sellers#invite'
        post :invite, to: 'waiting_sellers#do_invite'
      end
    end

    resources :problem_reports, path: 'problem-reports', only: [:index, :show] do
      member do
        post :resolve
        put :tag
      end
    end

    resources :product_orders, only: :index, path: 'product-orders'

    root to: 'root#index'
  end

  namespace :feedback do
    resources :problem_reports, path: 'problem-reports', only: [:new, :create]
  end

  get '/performance', to: 'performance#index'

  get '/contact', to: 'static#contact'
  get '/join-mailing-list', to: 'static#join_mailing_list'
  get '/privacy', to: 'static#privacy'
  get '/terms-of-use', to: 'static#terms_of_use'
  get '/accessibility', to: 'static#accessibility'
  get '/core-terms', to: 'static#core_terms'
  get '/guides/seller', to: 'static#seller_guide'
  get '/guides/buyer', to: 'static#buyer_guide'
  get '/license', to: 'static#license'
  # Health check page for load balancer - never use basic auth
  get '/health', to: 'static#health'
  get '/govdc', to: 'static#govdc'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root to: redirect('/cloud')
end

app/models/search/product.rb
module Search
  class Product < Base
    attr_reader :term, :section

    def initialize(args={})
      @section = args.delete(:section)
      term = args.delete(:term)

      if term.present?
        args[:selected_filters] ||= {}
        args[:selected_filters].merge!(term: term)
      end

      super(args)
    end

    def available_filters
      {
        term: :term_filter,
        audiences: audiences_keys,
        characteristics: [:data_in_australia, :api, :mobile_devices],
        pricing: [:free_version, :free_trial, :education, :not_for_profit],
        business_identifiers: [:disability, :indigenous, :not_for_profit, :regional, :start_up, :sme],
        reseller_type: [:reseller, :not_reseller],
        security_standards: security_standards_keys + [:irap_assessed, :asd_certified],
        government_network_type: government_network_type_keys
      }
    end

    def term
      filter_value(:term)
    end

  private
    include Concerns::Search::SellerTagFilters

    def base_relation
      ::Product.with_section(section).active
    end

    def apply_filters(scope)
      scope.yield_self(&method(:term_filter)).
            yield_self(&method(:audiences_filter)).
            yield_self(&method(:start_up_filter)).
            yield_self(&method(:sme_filter)).
            yield_self(&method(:disability_filter)).
            yield_self(&method(:regional_filter)).
            yield_self(&method(:indigenous_filter)).
            yield_self(&method(:not_for_profit_filter)).
            yield_self(&method(:reseller_filter)).
            yield_self(&method(:free_version_filter)).
            yield_self(&method(:free_trial_filter)).
            yield_self(&method(:education_pricing_filter)).
            yield_self(&method(:not_for_profit_pricing_filter)).
            yield_self(&method(:government_network_type_filter)).
            yield_self(&method(:data_location_filter)).
            yield_self(&method(:api_filter)).
            yield_self(&method(:mobile_devices_filter)).
            yield_self(&method(:security_standards_filter)).
            yield_self(&method(:irap_assessed_filter)).
            yield_self(&method(:asd_certified_filter))
    end

    def term_filter(relation)
      if term.present?
        relation = relation.basic_search(term)
      else
        relation
      end
    end

    def audiences_filter(relation)
      relation
      audiences_keys.each do |audience|
        if filter_selected?(:audiences, audience)
          relation = relation.with_audience(audience)
        end
      end
      relation
    end

    def government_network_type_filter(relation)
      government_network_type_keys.each do |type|
        if filter_selected?(:government_network_type, type)
          relation = relation.with_government_network_type(type)
        end
      end
      relation
    end

    def reseller_filter(relation)
      if filter_selected?(:reseller_type, :reseller)
        relation = relation.reseller
      end

      if filter_selected?(:reseller_type, :not_reseller)
        relation = relation.not_reseller
      end

      relation
    end

    def free_version_filter(relation)
      if filter_selected?(:pricing, :free_version)
        relation = relation.free_version
      else
        relation
      end
    end

    def free_trial_filter(relation)
      if filter_selected?(:pricing, :free_trial)
        relation = relation.free_trial
      else
        relation
      end
    end

    def education_pricing_filter(relation)
      if filter_selected?(:pricing, :education)
        relation = relation.education_pricing
      else
        relation
      end
    end

    def not_for_profit_pricing_filter(relation)
      if filter_selected?(:pricing, :not_for_profit)
        relation = relation.not_for_profit_pricing
      else
        relation
      end
    end

    def data_location_filter(relation)
      if filter_selected?(:characteristics, :data_in_australia)
        relation = relation.with_data_in_australia
      else
        relation
      end
    end

    def api_filter(relation)
      if filter_selected?(:characteristics, :api)
        relation = relation.with_api
      else
        relation
      end
    end

    def mobile_devices_filter(relation)
      if filter_selected?(:characteristics, :mobile_devices)
        relation = relation.mobile_devices
      else
        relation
      end
    end

    def security_standards_filter(relation)
      security_standards_keys.each do |standard|
        if filter_selected?(:security_standards, standard)
          relation = relation.send(standard)
        end
      end
      relation
    end

    def irap_assessed_filter(relation)
      if filter_selected?(:security_standards, :irap_assessed)
        relation = relation.irap_assessed
      else
        relation
      end
    end

    def asd_certified_filter(relation)
      if filter_selected?(:security_standards, :asd_certified)
        relation = relation.asd_certified
      else
        relation
      end
    end

    def audiences_keys
      ::Product.audiences.values
    end

    def government_network_type_keys
      ::Product.government_network_type.values
    end

    def security_standards_keys
      [
        :iso_27001, :iso_27017, :iso_27018, :csa_star, :pci_dss, :soc_2
      ]
    end
  end
end

app/controllers/ops/seller_applications/products_controller.rb
class Ops::SellerApplications::ProductsController < Ops::BaseController
  layout '../ops/seller_applications/_layout'

  def show
  end

private
  def application
    @application ||= SellerVersion.find(params[:seller_application_id])
  end
  helper_method :application

  def product
    @product ||= ProductDecorator.new(
      application.seller.products.find(params[:id]),
      view_context,
    )
  end
  helper_method :product
end

app/controllers/ops/seller_versions/products_controller.rb
class Ops::SellerVersions::ProductsController < Ops::BaseController
  layout '../ops/seller_versions/_layout'

  def show
  end

private
  def application
    @application ||= SellerVersion.find(params[:seller_application_id])
  end
  helper_method :application

  def product
    @product ||= ProductDecorator.new(
      application.seller.products.find(params[:id]),
      view_context,
    )
  end
  helper_method :product
end

app/controllers/pathways/products_controller.rb
class Pathways::ProductsController < ApplicationController

  def show; end

private

  def product
    @product ||= ProductDecorator.new(
      Product.active.with_section(section).find(params[:id]),
      view_context,
    )
  end
  helper_method :product

  def section
    params[:section]
  end
  helper_method :section

end

app/controllers/pathways/search_controller.rb
class Pathways::SearchController < ApplicationController
  helper Sellers::ProfilesHelper

private
  def search
    @search ||= Search::Product.new(
      term: params[:q],
      section: params[:section],
      selected_filters: params.except(:q, :section),
      page: params.fetch(:page, 1),
      per_page: 25,
    )
  end
  helper_method :search

  def section
    params[:section]
  end
  helper_method :section

end

app/controllers/sellers/applications/products_controller.rb
class Sellers::Applications::ProductsController < Sellers::Applications::BaseController
  layout '../sellers/applications/shared/_layout'
  before_action :ensure_cloud_services_provided!
  helper Sellers::ApplicationsHelper

  def index
  end

  def new
    @operation = run Sellers::SellerVersion::Products::Create do |result|
      return redirect_to sellers_application_product_path(result[:application_model], result[:product_model])
    end
  end

  def edit
    @operation = run Sellers::SellerVersion::Products::Update::Present
  end

  def update
    params[:seller_application] ||= {}

    @operation = run Sellers::SellerVersion::Products::Update do |result|
      flash.notice = I18n.t('sellers.applications.messages.changes_saved')
      return redirect_to sellers_application_product_path(result['model.application'], result['model.product'])
    end

    render :edit
  end

  def clone
    @operation = run Sellers::SellerVersion::Products::Clone do |result|
      flash.notice = I18n.t('sellers.applications.messages.product_cloned')
    end

    redirect_to sellers_application_products_path(application)
  end

  def destroy
    if product.destroy
      flash.notice = I18n.t('sellers.applications.messages.product_destroyed')
    end
    redirect_to sellers_application_products_path(application)
  end

  def self.contracts
    [
      Sellers::SellerVersion::Products::Contract::AvailabilitySupport,
      Sellers::SellerVersion::Products::Contract::BackupRecovery,
      Sellers::SellerVersion::Products::Contract::Basics,
      Sellers::SellerVersion::Products::Contract::Commercials,
      Sellers::SellerVersion::Products::Contract::DataProtection,
      Sellers::SellerVersion::Products::Contract::Environment,
      Sellers::SellerVersion::Products::Contract::IdentityAuthentication,
      Sellers::SellerVersion::Products::Contract::Locations,
      Sellers::SellerVersion::Products::Contract::OnboardingOffboarding,
      Sellers::SellerVersion::Products::Contract::OperationalSecurity,
      Sellers::SellerVersion::Products::Contract::ReportingAnalytics,
      Sellers::SellerVersion::Products::Contract::SecurityPractices,
      Sellers::SellerVersion::Products::Contract::SecurityStandards,
      Sellers::SellerVersion::Products::Contract::Terms,
      Sellers::SellerVersion::Products::Contract::Type,
      Sellers::SellerVersion::Products::Contract::UserData,
      Sellers::SellerVersion::Products::Contract::UserSeparation,
    ]
  end

  def self.steps
    contracts.map {|contract|
      Sellers::Applications::ProductStepPresenter.new(contract)
    }
  end

private
  def _run_options(options)
    if ['edit', 'update'].include?(action_name)
      options = options.merge(
        'config.contract_class' => contract_class,
      )
    end

    options.merge(
      'config.current_user' => current_user,
    )
  end

  def step
    self.class.steps.find {|step| step.slug == params[:step] } || raise(NotFound)
  end
  helper_method :step

  def contract_class
    step.contract_class if step.present?
  end

  def application
    @application ||= current_user.seller_versions.created.find(params[:application_id])
  end
  helper_method :application

  def products
    application.seller.products.order('name ASC')
  end
  helper_method :products

  def product
    @product ||= products.find(params[:id])
  end
  helper_method :product

  def progress_report
    @progress_report ||= SellerApplicationProgressReport.new(
      application: application,
      product_steps: self.class.steps,
      validate_optional_steps: true,
    )
  end
  helper_method :progress_report

  def presenter
    @presenter ||= Sellers::Applications::ProductDashboardPresenter.new(
      application, product, self.class.steps,
    )
  end
  helper_method :presenter

  def operation
    @operation
  end
  helper_method :operation

  def form
    operation["contract.default"]
  end
  helper_method :form

  def ensure_cloud_services_provided!
    unless application.services.include?('cloud-services')
      return redirect_to sellers_application_path(application)
    end
  end
end

app/helpers/ops/seller_versions/products_helper.rb
module Ops::SellerVersions::ProductsHelper
  include Ops::SellerVersionsHelper

  include Pathways::ProductsHelper
end

app/helpers/pathways/products_helper.rb
module Pathways::ProductsHelper

  def product_field(key, value)
    content_tag(:dt, key) +
      content_tag(:dd, product_value(value))
  end

  def product_value(value)
    case
    when value.is_a?(Array)
      content_tag(:ul) {
        value.map {|item| content_tag(:li, h(item)) }.join.html_safe
      }
    when value.is_a?(Date)
      value.strftime('%d/%m/%Y')
    when value.is_a?(Document)
      format_product_upload(value)
    when value.is_a?(TrueClass)
      'Yes'
    when value.is_a?(FalseClass)
      'No'
    else
      simpler_format(value)
    end
  end

  def format_product_upload(upload)
    if upload.document.blank?
      return 'Not provided'
    end

    out = [
      h(upload.original_filename)
    ]

    case upload.scan_status
    when 'clean'
      out << content_tag(:span, class: 'actions') do
        label = h("View document (#{upload.extension}, #{number_to_human_size(upload.size)})")
        link_to(label, upload.document.url, target: '_blank', title: 'Download this document')
      end
    when 'unscanned'
      out << '– awaiting virus scan'
    when 'infected'
      out << '– infected file'
    end

    out.join(' ').html_safe
  end

end

app/views/pathways/products/_additional_terms.html.erb
<% if product.display_additional_terms? %>
  <ul class="documents">
    <li>
      <span aria-hidden="true"></span>
      <%= link_to 'Additional terms', product.terms.document.url, target: 'blank' %>
      (<%= product.terms.extension %>, <%= number_to_human_size(product.terms.size) %>)
    </li>
  </ul>
<% end %>

app/views/pathways/products/_basics.html.erb
<div class="basics">
  <div class="summary">
    <dl>
      <% if product.is_reselling? %>
        <dt>Made by:</dt>
        <dd><%= product.organisation_resold %>
      <% end %>
      <dt>For:</dt>
      <dd>
        <ul>
          <% product.audiences.texts.each do |audience| %>
            <li><%= audience %>
          <% end %>
        </ul>
      </dd>
    </dl>
    <%= simpler_format product.summary %>

    <% if product.features.any? || product.benefits.any? %>
      <div class="product-section features-benefits">
        <% if product.features.any? %>
        <ul>
          <h2>Features</h2>
          <% product.features.each do |feature| %>
            <li><%= feature.feature %></li>
          <% end %>
        </ul>
        <% end %>

        <% if product.benefits.any? %>
        <ul>
          <h2>Benefits</h2>
          <% product.benefits.each do |benefit| %>
            <li><%= benefit.benefit %></li>
          <% end %>
        </ul>
        <% end %>
      </div>
    <% end %>

    <dl>
      <% if product.free_version? %>
        <dt>Free version details</dt>
        <dd><%= simpler_format product.free_version_details %></dd>
      <% end %>
      <% if product.free_trial? %>
        <dt>Free trial available</dt>
        <dd><%= link_to product.free_trial_url, product.free_trial_url %></dd>
      <% end %>
      <dt>Minimum price</dt>
      <dd><%= product.formatted_pricing_min %> <%= product.pricing_unit %></dd>
      <dt>Maximum price</dt>
      <dd><%= product.formatted_pricing_max %> <%= product.pricing_unit %></dd>
      <% if product.pricing_calculator_url.present? || product.pricing_variables.present? %>
        <% if product.pricing_calculator_url.present? %>
          <dt>Pricing calculator</dt>
          <dd><%= link_to product.pricing_calculator_url, product.pricing_calculator_url %></dd>
        <% end %>

        <dt>Variables affecting pricing</dt>
        <dd>
          <%= simpler_format product.pricing_variables %>
        </dd>
      <% end %>
      <% if product.education_pricing? %>
        <dt>Education pricing</dt>
        <dd>
          <dl class="nested">
            <dt>Eligibility</dt>
            <dd><%= simpler_format product.education_pricing_eligibility %></dd>
            <dt>Pricing differences</dt>
            <dd><%= simpler_format product.education_pricing_differences %></dd>
          </dl>
        </dd>
      <% end %>
      <% if product.not_for_profit_pricing? %>
        <dt>Not-for-profit pricing</dt>
        <dd>
          <dl class="nested">
            <dt>Eligibility</dt>
            <dd><%= simpler_format product.not_for_profit_pricing_eligibility %></dd>
            <dt>Pricing differences</dt>
            <dd><%= simpler_format product.not_for_profit_pricing_differences %></dd>
          </dl>
        </dd>
      <% end %>
    </dl>
  </div>

  <div class="actions">
    <dl class="product-metadata">
      <dt>Product ID</dt>
      <dd><%= product.id %></dd>
    </dl>

    <%= render partial: 'buy_product', locals: { product: product } %>
    <%= render partial: 'additional_terms', locals: { product: product } %>

    <div class="contact">
      <h2>Contact</h2>
      <div class="vcard">
        <span class="fn"><%= product.contact_name %></span>
        <span class="email"><%= mail_to product.contact_email, product.contact_email, "data-module" => "track-outbound-link" %></span>
        <% if product.contact_phone.present? %>
          <span class="tel"><%= tel_to product.contact_phone, "data-module" => "track-outbound-link" %></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pathways/products/_buy_product.html.erb
<% if current_user.present? && current_user.is_active_buyer? %>
  <%= link_to 'Buy this product', new_buyers_product_order_path(product), class: 'action' %>
<% else %>
  <div class="disabled-action-area">
    <%= link_to 'Become a registered buyer', registration_path('buyer') %> to purchase this product.
  </div>
<% end %>

app/views/pathways/products/show.html.erb
<% content_for :title, product.name %>
<% content_for :last_updated, I18n.localize(product.updated_at.localtime, format: :simple_date) %>

<section class="view-pathways-products-show">
  <header class="with-seller-details">
    <h1><%= content_for :title %></h1>
    <div class="seller">
      by <%= link_to product.seller.name, sellers_profile_path(product.seller) %>
      <% if product.is_reselling? %>
        <ul class="tags">
          <li>Reseller</li>
        </ul>
      <% end %>
    </div>
  </header>

  <%= render partial: 'basics', locals: { product: product } %>

  <div class="profile-container">
    <div class="contents-container">
      <div class="contents">
        <h3>On this page</h3>
        <ol>
          <% product.details.keys.each do |key| %>
            <li><%= link_to key, "##{key.parameterize}" %></li>
          <% end %>
        </ol>
      </div>
    </div>
    <div class="profile">
      <% product.details.each do |heading, details| %>
        <dl id="<%= heading.parameterize %>">
          <h2><%= heading %></h2>
          <% details.each do |key, value| %>
            <%= product_field(key, value) %>
          <% end %>
        </dl>
      <% end %>
    </div>
</section>